development:
  sessions:
    default:
      database: scrapybara_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: scrapybara_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: scrapybara_production
      hosts:
        - localhost:27017